### ISSUE TITLE
Boole Fork Wish List

### ISSUE THREAD

**Issue by GalRogozinski** [ssvlabs/SIPs#39]
## Description

An ever-updated list of changes we want that need a fork.

### In
- [ ] #43 (performance & scalability)
- [ ] #61  (performance & scalability)
- [ ] #65 (security)
### Out
- [ ] #63 (performance)
- [ ] #67 (security) (because it isn't a forking change)
- [ ] [If not QBFT leader, do not wait for start value](https://github.com/ssvlabs/ssv-spec/pull/371) - less important because currently no issues with proposals.
  **Prerequisites:**
  - [ ] #37 
  - [ ] https://github.com/ssvlabs/ssv-spec/pull/352
- [ ] https://github.com/ssvlabs/ssv-spec/issues/532
- [ ] #58 - probably lots of work
- [ ] https://github.com/ssvlabs/ssv-spec/issues/373 - No issues with proposals
- [ ] #59 
- [ ] https://github.com/ssvlabs/ssv-spec/pull/355

**Comment by GalRogozinski** [comment]
This list was continued in https://github.com/ssvlabs/ssv-spec/issues/368

**Comment by GalRogozinski** [comment]
@moshe-blox 
you mean https://github.com/ssvlabs/ssv-spec/pull/371? we can do it

**Comment by MatheusFranco99** [comment]
[Fork: QBFT Identifier with fixed length -> msg encoding changes](https://github.com/ssvlabs/ssv-spec/pull/536)

**Comment by MatheusFranco99** [comment]
Remove repeated Signer field in `spec.types.PartialSignatureMessage` (already exists in `spec.types.PartialSignatureMessages`).

**Comment by GalRogozinski** [comment]
Moved to #77
